#!/bin/sh

export LD_LIBRARY_PATH=$ORIGINAL_LD_LIBRARY_PATH
export CUDA_HOME=$ORIGINAL_CUDA_HOME
export PATH=${ORIGINAL_PATH}
export CPATH=${ORIGINAL_CPATH}
unset ORIGINAL_LD_LIBRARY_PATH
unset ORIGINAL_CUDA_HOME
unset ORIGINAL_PATH
unset ORIGINAL_CPATH
unset DESIRED_CUDA_VERSION
