name: ci
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Shellcheck utils
        run: shellcheck utils/*.sh
      - name: Shellcheck env
        run: shellcheck pytorch3d/*.sh